FROM alpine:3.11.2

# install common lisp
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  sbcl \
  openjdk12-jdk openjdk12-jre \
  gcc g++ \
  python2 python3 \
  ruby
